### ISSUE TITLE
Add support for the property spread

### ISSUE THREAD

**Issue by gajus** [davidwaterston/eslint-plugin-objects#10]
Spec: https://github.com/sebmarkbage/ecmascript-rest-spread

Subject code that triggers error:

``` js
style = {
    ...this.props.style
}
```

Error:

```
TypeError: Cannot read property 'loc' of undefined
    at EventEmitter.checkObjectExpression (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/eslint-plugin-objects/lib/rules/no-object-property-split.js:15:60)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/util/traverser.js:38:33)
    at EventEmitter.module.exports.api.verify (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/eslint.js:840:23)
    at processText (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/cli-engine.js:187:27)
    at CLIEngine.executeOnText (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/node_modules/eslint/lib/cli-engine.js:672:26)
    at exports.default (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/dist/syntaxes/js/lintText.js:23:16)
    at exports.default (/Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/dist/utilities/lintText.js:39:35)
    at /Users/gajus/Documents/dev/applaudience/showtime-ad-app/node_modules/canonical/dist/utilities/lintFiles.js:44:49
```

**Comment by gajus** [comment]
Relevant code:

```
import fecha from 'fecha';
import Immutable from 'immutable';
import {
    createInitialState as createLocationForm
} from '@applaudience/react-showtimes-location-form';
import {
    createInitialState as createCalendarState
} from '@applaudience/react-showtimes-calendar';
import {
    createInitialState as createEventsState
} from '@applaudience/react-showtimes-events';
import createAnalyticsState from './analytics/createInitialState';
import config from './../config';
import normalizeCampaignParameters from './lib/normalizeCampaignParameters';
import queryString from 'query-string';

const initialState = {
    activeCenter: null,
    appUI: {
        isExpanded: false
    },
    calendar: {
        ...createCalendarState()
    },
    cinemas: Immutable.Set(),
    events: {
        activeQuery: null,
        data: {},
        errorMessage: '',
        isFakingBusy: false,
        isFetching: false
    },
    eventsUI: createEventsState(),
    locationForm: createLocationForm(),
    nearbyLocations: {
        data: [],
        errorMessage: '',
        isFetching: false
    }
};

const campaign = normalizeCampaignParameters(global.CAMPAIGN || queryString.parse(global.location.search));

if (!global.USER) {
    throw new Error('USER global variable is not set.');
}

initialState.analytics = createAnalyticsState({
    appVersion: config.get('appVersion'),
    ipAddress: global.USER.ip,
    location: global.USER.location.coordinates
});

initialState.activeCenter =  config.get('defaultLocation').toJS();

if (!campaign) {
    throw new Error('A valid Campaign was not provided.');
}

initialState.campaign = {
    activeDate: campaign.fromDate,
    ...campaign,
    fromDate: campaign.fromDate,
    numberOfDates: campaign.numberOfDatesToDisplay
};

initialState.calendar = {
    activeDate: initialState.campaign.fromDate,
    firstVisibleIndex: 0,
    language: initialState.campaign.language,
    numberOfDatesToDisplay: initialState.campaign.numberOfDates,
    startDate: initialState.campaign.fromDate
};

initialState.appUI.isExpanded = Boolean(initialState.campaign.isInitiallyExpanded);

export default Immutable.fromJS(initialState);
```

**Comment by gajus** [comment]
@davidwaterston Can this be assigned "bug" label?

**Comment by gajus** [comment]
It looks like it is the:

```js
style = {
    ...this.props.style
}
```

that triggers the error.

**Comment by manovotny** [comment]
This error bit me last night too. 

I tried working on a fix for a while, but wound up stumped. 😞

**Comment by manovotny** [comment]
Ok, I did a little more fiddling.

I wouldn't say it "adds support" for spread operators, but it stops the bleeding.

You could add the following code in `no-object-property-split.js`, at the very top of the [for loop checking keys and values](https://github.com/davidwaterston/eslint-plugin-objects/blob/master/lib/rules/no-object-property-split.js#L14) to essentially skip checking spread operators, which will not have keys / values and cannot be split on multiple lines.

``` js
if (props[i].type === 'ExperimentalSpreadProperty') {
    continue;
}
```

However, `ExperimentalSpreadProperty` was not added until ESLint 1.0.0-rc-1 (see [release notes](http://eslint.org/blog/2015/07/eslint-1.0.0-rc-1-released#new-language-features)), which means `eslint-plugin-objects` would need to [up the minimum required version of eslint](https://github.com/davidwaterston/eslint-plugin-objects/blob/master/package.json#L15) to use this check.
